server:
  port: 7001
eureka:
  instance:
    hostname: localhost # 本机
    prefer-ip-address: true
  server:
    #关闭自我保护机制，防止失效的服务也被一直访问 （开发环境)
    enable-self-preservation: false
    #该配置可以修改检查失效服务的时间，每隔5s检查失效服务，默认该配置是 60s （开发环境)
    eviction-interval-timer-in-ms: 3000
  client:
    registerWithEureka: false  #不注册
    fetchRegistry: false  #不获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机注册中心的地址
      #defaultZone: http://localhost:7002/eureka/ #多机注册中心的地址 多个用逗号隔开